apiVersion: v1
kind: Service
metadata:
  name: opendeepwiki-backend
  namespace: opendeepwiki
  labels:
    app.kubernetes.io/name: opendeepwiki
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: opendeepwiki
    app.kubernetes.io/component: backend
---
apiVersion: v1
kind: Service
metadata:
  name: opendeepwiki-frontend
  namespace: opendeepwiki
  labels:
    app.kubernetes.io/name: opendeepwiki
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: opendeepwiki
    app.kubernetes.io/component: frontend
